# Generated by Django 6.0 on 2026-01-22 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Organizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=300)),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('localizacao', models.CharField(max_length=200)),
                ('Lotacao', models.PositiveBigIntegerField()),
                ('preco', models.IntegerField()),
                ('status', models.CharField(choices=[('A', 'ATIVO'), ('L', 'Lotado'), ('C', 'Concluido'), ('X', 'Cancelado')], default='A', max_length=10)),
                ('inscritos', models.IntegerField(blank=True, null=True)),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizador_eventos', to='core.organizador')),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='participante', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pagamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pago', models.IntegerField()),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('C', 'Concluido'), ('X', 'Cancelado'), ('R', 'Reembolsado')], default='P', max_length=12)),
                ('ativo', models.BooleanField(default=False)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='core.eventos')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='core.participante')),
            ],
        ),
        migrations.CreateModel(
            name='Inscricoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('C', 'Confirmada'), ('X', 'Cancelada'), ('R', 'Reembolsado')], default='P', max_length=1)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('pago', models.BooleanField(default=False)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='core.eventos')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscritos', to='core.participante')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('confirmacao_inscricao', 'Confirmação de Inscrição'), ('evento_criado', 'Evento Criado'), ('lembrete', 'Lembrete de Evento'), ('cancelamento', 'Cancelamento de Evento'), ('reembolso', 'Reembolso do Evento')], max_length=30)),
                ('assunto', models.CharField(max_length=150)),
                ('mensagem', models.TextField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado'), ('erro', 'Erro ao Enviar')], default='pendente', max_length=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('enviado', models.BooleanField(default=False)),
                ('tentativas', models.PositiveIntegerField(default=0)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='core.eventos')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='core.participante')),
            ],
        ),
    ]
